from dataclasses import dataclass
from enum import Enum, auto


class ProblemCheckerVerdict(Enum):
    """! Verdicts of problem checkers enumeration class."""

    # Output is correct.
    Correct = auto()
    # Output is incorrect.
    Incorrect = auto()
    # Output format is incorrect.
    PresentationError = auto()
    # Checker crashes.
    Crashed = auto()


@dataclass
class ProblemCheckerTest:
    """! A test scenario of problem checker dataclass."""

    """! Test ID.

    * It must be auto-generated by using UUID.
    * It must be read-only.

    TODO: Set UUID generator as a default_factory.
    """
    _id: str

    """! Input data."""
    input: str

    """! Custom output data."""
    output: str

    """! Correct output data."""
    answer: str

    """! Expected verdict of checker."""
    expected: ProblemCheckerVerdict
