from dataclasses import dataclass
from enum import Enum, auto

from .SourceCode import SourceCode


class ProblemSolutionType(Enum):
    """! Types of problem solutions enumeration class."""

    # Main model correct.
    ModelCorrect = auto()
    # Correct.
    Correct = auto()
    # Incorrect.
    Incorrect = auto()


@dataclass(kw_only=True)
class ProblemSolution:
    """! A problem's solution dataclass."""

    """! Solution ID.

    * It must be auto-generated by using UUID.
    * It must be read-only.

    TODO: Set UUID generator as a default_factor.
    """
    _id: str

    """! Solution code author."""
    # author: GithubUser

    """! Solution name.

    * It must be non-empty.
    """
    name: str

    """! Solution source code."""
    code: SourceCode

    """! Solution type."""
    type: ProblemSolutionType
