from abc import ABC
from dataclasses import dataclass


@dataclass(kw_only=True)
class ProblemPublicTest:
    """! A problem's public test dataclass."""

    """! Input data."""
    input: str

    """! Custom output data.

    It may not be correct output.
    """
    output: str

    """! Whether to verify the output."""
    verify_output: bool = False


@dataclass(kw_only=True)
class ProblemTest(ABC):
    """! A problem's secret test dataclass."""

    """! Problem ID.

    * It must be auto-generated by using UUID.
    * It must be read-only.

    TODO: Set UUID generator as a default_factory.
    """
    _id: str

    # TODO: Define attributes.


@dataclass(kw_only=True)
class ProblemTestRaw(ProblemTest):
    """! A text-raw secret test dataclass."""

    """! Input data."""
    input: str


@dataclass(kw_only=True)
class ProblemTestScript(ProblemTest):
    """! A script-based secret test dataclass."""

    """! Script to generate input data."""
    # TOOD: Consider using SourceCode of langauge 'bash'.
    script: str
