from dataclasses import dataclass
from enum import Enum, auto

from .SourceCode import SourceCode


class ProblemSolutionType(Enum):
    """! Types of problem solutions enumeration class."""

    # Main correct (model solution).
    MainCorrect = auto()
    # Correct.
    Correct = auto()
    # Incorrect.
    Incorrect = auto()


@dataclass(kw_only=True)
class ProblemSolution:
    """! A problem's solution dataclass."""

    """! Solution ID.

    * It must be auto-generated by using UUID.
    * It must be read-only.
    """
    _id: str

    """! Solution code author."""
    author: str

    """! Solution name.

    * It must be non-empty.
    """
    name: str

    """! Solution source code."""
    code: SourceCode

    """! Solution type."""
    type: ProblemSolutionType

    @property
    def id(self) -> str:
        return self._id
